// Generated by gencpp from file srl_origami_manipulator/motorCmd.msg
// DO NOT EDIT!


#ifndef SRL_ORIGAMI_MANIPULATOR_MESSAGE_MOTORCMD_H
#define SRL_ORIGAMI_MANIPULATOR_MESSAGE_MOTORCMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace srl_origami_manipulator
{
template <class ContainerAllocator>
struct motorCmd_
{
  typedef motorCmd_<ContainerAllocator> Type;

  motorCmd_()
    : motor_cmd()  {
    }
  motorCmd_(const ContainerAllocator& _alloc)
    : motor_cmd(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _motor_cmd_type;
  _motor_cmd_type motor_cmd;





  typedef boost::shared_ptr< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> const> ConstPtr;

}; // struct motorCmd_

typedef ::srl_origami_manipulator::motorCmd_<std::allocator<void> > motorCmd;

typedef boost::shared_ptr< ::srl_origami_manipulator::motorCmd > motorCmdPtr;
typedef boost::shared_ptr< ::srl_origami_manipulator::motorCmd const> motorCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::srl_origami_manipulator::motorCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace srl_origami_manipulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'srl_origami_manipulator': ['/home/shared/ws/src/srl_origami_manipulator/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "091b2c9cf1f930ed90809c60dc039030";
  }

  static const char* value(const ::srl_origami_manipulator::motorCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x091b2c9cf1f930edULL;
  static const uint64_t static_value2 = 0x90809c60dc039030ULL;
};

template<class ContainerAllocator>
struct DataType< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "srl_origami_manipulator/motorCmd";
  }

  static const char* value(const ::srl_origami_manipulator::motorCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[] motor_cmd\n\
";
  }

  static const char* value(const ::srl_origami_manipulator::motorCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motor_cmd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motorCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::srl_origami_manipulator::motorCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::srl_origami_manipulator::motorCmd_<ContainerAllocator>& v)
  {
    s << indent << "motor_cmd[]" << std::endl;
    for (size_t i = 0; i < v.motor_cmd.size(); ++i)
    {
      s << indent << "  motor_cmd[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.motor_cmd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SRL_ORIGAMI_MANIPULATOR_MESSAGE_MOTORCMD_H
